### PR TITLE
Layer search refactor

### PR DESCRIPTION
**Pull request by jackbackes**
### Summary
This pull request introduces a refactor of the Hierarchical Navigable Small World (HNSW) search implementation and the handling of node neighbors. The changes include the introduction of a new Layer enum, a new HasNeighbors trait, and modifications to the search_single_layer and search_zero_layer methods. The overall goal of these changes is to improve code readability and maintainability.

### Changes
Introduction of Layer Enum: A new enum Layer has been introduced to represent the different layers of the HNSW graph. The enum has two variants: Zero for the zero layer and NonZero(T) for non-zero layers. This enum is used to simplify the handling of different layers in the search_single_layer method.

Introduction of HasNeighbors Trait: A new trait HasNeighbors has been introduced to abstract the retrieval of neighbors from nodes. The trait defines a method get_neighbors that returns an iterator over the neighbors of a node. This trait is implemented for both NeighborNodes (nodes in the zero layer) and Node (nodes in non-zero layers).

Refactor of search_single_layer Method: The search_single_layer method has been refactored to use the Layer enum and the HasNeighbors trait. The method now takes an additional parameter layer: Layer<&[Node<M>]> to specify the layer in which the search is to be performed. The method uses pattern matching on the layer parameter to handle the zero layer and non-zero layers differently. The use of the HasNeighbors trait allows for a more concise and unified way to retrieve neighbors from nodes.

Refactor of search_zero_layer Method: The search_zero_layer method has been refactored to call the search_single_layer method with the Layer::Zero variant. This change simplifies the code and reduces redundancy.

Other Changes: The rest of the hnsw class has been updated to use the new Layer enum and HasNeighbors trait. These changes include updates to the add_neighbor method, the handling of node creation, and the retrieval of neighbors in different parts of the code.

### Impact
These changes improve the code structure and make it easier to understand and maintain. The introduction of the Layer enum and the HasNeighbors trait provides a more unified and abstract way to handle different layers and node neighbors. The refactoring of the search methods reduces code redundancy and improves code readability.

Testing:
All existing tests have passed. As this was a refactor, no additional tests are necessary, as the Rust compiler has checked to ensure all code branches are safe.

### CODE REVIEW

**Comment by thejohnbackes** [comment]
Resolves this issue: #3

**Comment by thejohnbackes** [comment]
@vadixidav let me know if you have any comments on my fix! Thanks for doing the hard work on this package.

**Comment by vadixidav** [comment]
I have been quite busy, but I will try to find some time later today or tomorrow to review this (and the other PR that came in recently). Thanks for contributing.

**Comment by jackbackes** [comment]
Thanks! Do you think you'll have a chance to take a look soon?

**Comment by jackbackes** [comment]
Hi @vadixidav - will you have a chance to look at this soon?

**Comment by vadixidav** [comment]
I asked @xd009642 to take a look when they get a chance. I do apologize for my lack of maintainership on this. Hopefully all of the active PRs and issues can be addressed. We are definitely lacking maintainer time currently.

**Review by xd009642 — APPROVED** [review]
Looks good to me! I'd probably consider some doc comments on the `Layer` enum and maybe `HasNeighbors` trait, but functionally the code all looks good.

I can see a few things lack doc comments anyway in the public API so I wouldn't call that a blocker to merge (I may go over and do some doc PRs as I get more familiar with the project anyway).

**Pull request merged**
